spring:
  application:
    name: user-service
  r2dbc:
    #url: r2dbc:h2:file:///./userdb
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: passer

server:
  port: 8092
#debug: true